# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VCCzvx8XFc7viA19xVA3pOnP54Qgt7aT
"""

import numpy as np


# ── Activation functions ─────────────────────────────────────────────────────

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def tanh(x):
    return np.tanh(x)


# ── LSTM Parameters (from PDF) ────────────────────────────────────────────────

# Weights for forget gate   (Wf, Uf, bf)
Wf = np.array([[0.5]])
Uf = np.array([[0.6]])
bf = np.array([0.1])

# Weights for input gate    (Wi, Ui, bi)
Wi = np.array([[0.7]])
Ui = np.array([[0.8]])
bi = np.array([0.1])

# Weights for candidate     (Wc, Uc, bc)
Wc = np.array([[0.9]])
Uc = np.array([[0.7]])
bc = np.array([0.0])

# Weights for output gate   (Wo, Uo, bo)
Wo = np.array([[0.6]])
Uo = np.array([[0.5]])
bo = np.array([0.1])

# Output layer weights (linear: y_hat = Wy * h + by)
Wy = np.array([[1.0]])
by = np.array([0.0])

# Initial states
h = np.array([0.0])   # hidden state  h_0
c = np.array([0.0])   # cell state    c_0

# Input sequence
inputs = [1.0, 2.0, 3.0, 4.0]


# ── LSTM Forward Pass ─────────────────────────────────────────────────────────

print("=" * 55)
print("  LSTM Numerical Example — Step-by-step Forward Pass")
print("=" * 55)

for t, x_t in enumerate(inputs, start=1):
    x = np.array([x_t])

    # 1. Forget gate
    f = sigmoid(Wf @ x + Uf @ h + bf)

    # 2. Input gate
    i = sigmoid(Wi @ x + Ui @ h + bi)

    # 3. Candidate cell state
    c_tilde = tanh(Wc @ x + Uc @ h + bc)

    # 4. Cell state update
    c = f * c + i * c_tilde

    # 5. Output gate
    o = sigmoid(Wo @ x + Uo @ h + bo)

    # 6. Hidden state update
    h = o * tanh(c)

    print(f"\n── Time Step t={t}, Input x={x_t} ──────────────────")
    print(f"  Forget gate    f  = sigmoid({Wf[0,0]}*{x_t} + {Uf[0,0]}*h + {bf[0]:.1f}) = {f[0]:.4f}")
    print(f"  Input gate     i  = sigmoid({Wi[0,0]}*{x_t} + {Ui[0,0]}*h + {bi[0]:.1f}) = {i[0]:.4f}")
    print(f"  Candidate      c̃  = tanh({Wc[0,0]}*{x_t} + {Uc[0,0]}*h + {bc[0]:.1f})   = {c_tilde[0]:.4f}")
    print(f"  Cell state     c  = f*c_prev + i*c̃               = {c[0]:.4f}")
    print(f"  Output gate    o  = sigmoid({Wo[0,0]}*{x_t} + {Uo[0,0]}*h + {bo[0]:.1f}) = {o[0]:.4f}")
    print(f"  Hidden state   h  = o * tanh(c)                  = {h[0]:.4f}")


# ── Final Prediction ──────────────────────────────────────────────────────────

y_hat = Wy @ h + by

print("\n" + "=" * 55)
print("  Final Prediction")
print("=" * 55)
print(f"  y_hat = Wy * h + by = {Wy[0,0]} * {h[0]:.4f} + {by[0]}")
print(f"  Predicted value : {y_hat[0]:.4f}")
print(f"  Expected value  : ~4.0")
print(f"  ✓ The LSTM predicts ≈ {y_hat[0]:.1f}, close to 4")
print("=" * 55)